### ISSUE TITLE
Crashes if you wait at the intro screen

### ISSUE THREAD

**Issue by dlon** [pygame/stuntcat#50]
```
Traceback (most recent call last):
  File "run_game.py", line 3, in <module>
    stuntcat.cli.main()
  File "C:\Users\David\Documents\dev\pygame\stuntcat\stuntcat\cli.py", line 57, in main
    main(sys.argv)
  File "C:\Users\David\Documents\dev\pygame\stuntcat\stuntcat\main.py", line 6, in main
    gamemain(args)
  File "C:\Users\David\Documents\dev\pygame\stuntcat\stuntcat\main.py", line 14, in gamemain
    Game().mainloop()
  File "C:\Users\David\Documents\dev\pygame\stuntcat\stuntcat\game.py", line 101, in mainloop
    self.render()
  File "C:\Users\David\Documents\dev\pygame\stuntcat\stuntcat\game.py", line 69, in render
    rects = ascene.render()
  File "C:\Users\David\Documents\dev\pygame\stuntcat\stuntcat\scenes\cat3.py", line 734, in render
    rects.extend(self.render_sprites())
  File "C:\Users\David\Documents\dev\pygame\stuntcat\stuntcat\scenes\cat3.py", line 725, in render_sprites
    self.allsprites.update()
  File "C:\Python37\lib\site-packages\pygame-1.9.5.dev0-py3.7-win-amd64.egg\pygame\sprite.py", line 463, in update
    s.update(*args)
  File "C:\Users\David\Documents\dev\pygame\stuntcat\stuntcat\scenes\cat3.py", line 446, in update
    location = self.cat_holder.cat_head_location
AttributeError: 'CatUniScene' object has no attribute 'cat_head_location'
```

**Comment by illume** [comment]
Thanks :)
