### ISSUE TITLE
AttributeError: module 'pymunk' has no attribute 'inf'

### ISSUE THREAD

**Issue by AokiAhishatsu** [pygame/stuntcat#70]
```
Microsoft Windows [Version 10.0.19042.685]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\xeno>python -m stuntcat
C:\Program Files\Python38\python.exe: No module named stuntcat

C:\Users\xeno>python -V
Python 3.8.5

C:\Users\xeno>pip install stuntcat
Defaulting to user installation because normal site-packages is not writeable
Collecting stuntcat
  Downloading stuntcat-0.2.0-py2.py3-none-any.whl (5.5 MB)
     |████████████████████████████████| 5.5 MB 819 kB/s
Collecting pytmx
  Downloading PyTMX-3.24-py3-none-any.whl (21 kB)
Collecting pyscroll
  Using cached pyscroll-2.19.2.tar.gz (17 kB)
Collecting pymunk>=5.4.2
  Downloading pymunk-6.0.0-cp38-cp38-win_amd64.whl (280 kB)
     |████████████████████████████████| 280 kB 1.6 MB/s
Collecting pygame
  Downloading pygame-2.0.1-cp38-cp38-win_amd64.whl (5.2 MB)
     |████████████████████████████████| 5.2 MB 939 kB/s
Collecting thorpy
  Downloading thorpy-1.7-py2.py3-none-any.whl (422 kB)
     |████████████████████████████████| 422 kB 3.3 MB/s
Collecting cffi>1.14.0
  Downloading cffi-1.14.4-cp38-cp38-win_amd64.whl (179 kB)
     |████████████████████████████████| 179 kB 6.8 MB/s
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 2.2 MB/s
Using legacy 'setup.py install' for pyscroll, since package 'wheel' is not installed.
Installing collected packages: pytmx, pygame, pyscroll, pycparser, cffi, pymunk, thorpy, stuntcat
    Running setup.py install for pyscroll ... done
  WARNING: The script stuntcat.exe is installed in 'C:\Users\xeno\AppData\Roaming\Python\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed cffi-1.14.4 pycparser-2.20 pygame-2.0.1 pymunk-6.0.0 pyscroll-2.19.2 pytmx-3.24 stuntcat-0.2.0 thorpy-1.7
WARNING: You are using pip version 20.2.2; however, version 20.3.3 is available.
You should consider upgrading via the 'c:\program files\python38\python.exe -m pip install --upgrade pip' command.

C:\Users\xeno>python -m stuntcat
pygame 2.0.1 (SDL 2.0.14, Python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\Python38\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Program Files\Python38\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\xeno\AppData\Roaming\Python\Python38\site-packages\stuntcat\__init__.py", line 6, in <module>
    from stuntcat import game
  File "C:\Users\xeno\AppData\Roaming\Python\Python38\site-packages\stuntcat\game.py", line 16, in <module>
    from stuntcat.scenes import Scene
  File "C:\Users\xeno\AppData\Roaming\Python\Python38\site-packages\stuntcat\scenes\__init__.py", line 11, in <module>
    from .platformer.platformer import PlatformerScene
  File "C:\Users\xeno\AppData\Roaming\Python\Python38\site-packages\stuntcat\scenes\platformer\platformer.py", line 19, in <module>
    from . import unicyclecat
  File "C:\Users\xeno\AppData\Roaming\Python\Python38\site-packages\stuntcat\scenes\platformer\unicyclecat.py", line 56, in <module>
    def make_body(rect, moment=pymunk.inf):
AttributeError: module 'pymunk' has no attribute 'inf'
```

**Comment by AokiAhishatsu** [comment]
[Change in pymunk](https://github.com/viblo/pymunk/commit/b5d3b64485817819a399c582e3fb82dafd0a53c3#diff-5d8fe928eb0045c19b5cdf6e1edf302b9a69fbe0d8f54d445210555347d2dcb1)

**Comment by AokiAhishatsu** [comment]
Changing line 56 in  _\scenes\platformer\unicyclecat.py_ to `def make_body(rect, moment=float("inf")):` fixed it

**Comment by xandark** [comment]
I notice that this is fixed in git main, but it's not fixed in PyPI. Doing 

```
pip3 install --user --upgrade stuntcat
stuntcat
```

...recreates the error.

Maybe this bug should be updated to get the PyPI version current?
