### ISSUE TITLE
AttributeError: module 'pymunk' has no attribute 'inf

### ISSUE THREAD

**Issue by mustafakcali** [pygame/stuntcat#72]
pygame 2.1.2 (SDL 2.0.18, Python 3.10.7)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "c:\Users\my\Desktop\Uygulamalar\Dinozor.py", line 11, in <module>
    dino.start_physics(stable=True , bounciness= 0)
  File "C:\Users\my\AppData\Local\Programs\Python\Python310\lib\site-packages\play\play.py", line 718, in start_physics
    self.physics = _Physics(
  File "C:\Users\my\AppData\Local\Programs\Python\Python310\lib\site-packages\play\play.py", line 768, in __init__
    self._make_pymunk()
  File "C:\Users\my\AppData\Local\Programs\Python\Python310\lib\site-packages\play\play.py", line 779, in _make_pymunk
    moment = _pymunk.inf
AttributeError: module 'pymunk' has no attribute 'inf

**Comment by xandark** [comment]
I notice that this is fixed in git main, but it's not fixed in PyPI. Doing 

```
pip3 install --user --upgrade stuntcat
stuntcat
```

...recreates the error.

Maybe this bug should be updated to get the PyPI version current?
