### ISSUE TITLE
Tried install on GhostBSD

### ISSUE THREAD

**Issue by AokiAhishatsu** [pygame/stuntcat#84]
```
xeno@xeno-ghostbsd-pc /u/h/x/Desktop [1]> sudo pip install stuntcat
Collecting stuntcat
  Downloading stuntcat-0.2.4-py2.py3-none-any.whl.metadata (5.7 kB)
Collecting pygame (from stuntcat)
  Downloading pygame-2.5.2.tar.gz (15.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.8/15.8 MB 28.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      Skipping Cython compilation
      
      
      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using UNIX configuration...
      
      dpkg-architecture: warning: cannot determine CC system type, falling back to default (native compilation)
      /bin/sh: sdl2-config: not found
      /bin/sh: sdl2-config: not found
      /bin/sh: sdl2-config: not found
      
      Hunting dependencies...
      
      ---
      For help with compilation see:
          https://www.pygame.org/wiki/Compilation
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---
      
      Traceback (most recent call last):
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-qf43r5xh/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-qf43r5xh/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-qf43r5xh/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-qf43r5xh/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 409, in <module>
        File "/tmp/pip-install-ah6kqbra/pygame_89e285dfb7b14cbaafc1365acce75e4f/buildconfig/config.py", line 231, in main
          deps = CFG.main(**kwds, auto_config=auto)
        File "/tmp/pip-install-ah6kqbra/pygame_89e285dfb7b14cbaafc1365acce75e4f/buildconfig/config_unix.py", line 218, in main
          DependencyProg('SDL', 'SDL_CONFIG', 'sdl2-config', '2.0', ['sdl']),
        File "/tmp/pip-install-ah6kqbra/pygame_89e285dfb7b14cbaafc1365acce75e4f/buildconfig/config_unix.py", line 43, in __init__
          self.ver = config[0].strip()
      IndexError: list index out of range
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output
```

**Comment by illume** [comment]
TIL GhostBSD. Looks cool!

I know this is a very old issue.. but anyway…

You can get pygame on FreeBSD https://www.freshports.org/devel/py-game

I guess it uses the same packages.
